---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  dex.config: |
    connectors:
    - type: github
      id: github 
      name: GitHub
      config:
        clientID: <CLIENT_ID>
        clientSecret: <CLIENT_SECRET_ID>
        orgs:
        - name: <GITHUB_ORG>