apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yml
- service_canary.yml
- ingress.yml
images:
- name: humancat-frontend-canary-rollout-image
  newName: 909622006439.dkr.ecr.ap-northeast-2.amazonaws.com/humancat-frontend
  newTag: "20231009.231007"
namespace: gitops
