apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: 3
  updateStrategy:
    type: RollingUpdate  # ArgoCD 업데이트를 위한 설정
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.3
          command:
            - sh
            - -c
            - |
              export KAFKA_NODE_ID=$(echo ${HOSTNAME} | awk -F'-' '{print $NF}');
              export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://${HOSTNAME}.kafka-headless:9092";
              exec /etc/confluent/docker/run
          ports:
            - containerPort: 9092
              name: broker
            - containerPort: 29092
              name: controller
          env:
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka-0.kafka-headless:29092,1@kafka-1.kafka-headless:29092,2@kafka-2.kafka-headless:29092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:29092"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: CLUSTER_ID
              value: "bgeZzj2yQhyQLEix3qTsyg"