apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      instance: kafka-1
  template:
    metadata:
      labels:
        app: kafka
        instance: kafka-1
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.3
          ports:
            - containerPort: 9092
            - containerPort: 29092
          envFrom:
            - configMapRef:
                name: kafka-config
          env:
            - name: KAFKA_NODE_ID
              value: "0"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka-1:29092,1@kafka-2:29093,2@kafka-3:29094"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-1:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:29092"
