apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - name: kafka-1
      port: 9092
      targetPort: 9092
    - name: kafka-2
      port: 9093
      targetPort: 9093
    - name: kafka-3
      port: 9094
      targetPort: 9094
  clusterIP: None  # Headless Service
