apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
images:
- name: humancat-backend-image
  newName: AWSECR/humancat-backend
  newTag: 0.0.1-backend.01
namespace: gitops