apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: humancat-frontend-rollout
  
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: humancat-frontend-rollout
  template:
    metadata:
      name: humancat-frontend-rollout
      labels:
        app: humancat-frontend-rollout
    spec:
      containers:
        - name: humancat-frontend-rollout
          image: humancat-frontend-rollout-image
          envFrom:
            - configMapRef:
                name: backend-conf
     