apiVersion: apps/v1
kind: Deployment
metadata:
  name: humancat-blockend
spec:
  selector:
    matchLabels:
      app: humancat-backend
  template:
    metadata:
      name: humancat-backend
      labels:
        app: humancat-backend
    spec:
      containers:
        - name: humancat-backend
          image: humancat-backend-image
